name: CI - Build and Push Docker Images to ECR

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

jobs:
  authenticate_and_login:
    name: Authenticate with AWS and Login to ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN_ECR_PUSHER }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Verify ECR Login
        if: steps.login-ecr.outputs.registry
        run: |
          echo "Successfully logged in to ECR."
          echo "ECR Registry URI: ${{ steps.login-ecr.outputs.registry }}"